### ISSUE TITLE
[BUG] error when aligning wsinfer output: "'data' must be of a vector type, was 'NULL'"

### ISSUE THREAD

**Issue by kaczmarj** [SBU-BMI/tumor-til-survival-analysis#11]
i get the following error while aligning tumor and TIL files using wsinfer outputs. this failed on sample number 361, so there is probably some edge case that is not handled. interestingly, the ratio is 1.7857 when for all previous slides, it was 1.75. i am not sure if that is relevant to the problem.

```r
[1] "Sample 361: 1.78571428571429"
Error in matrix(unlist(ini), ncol = 2, byrow = TRUE) : 
  'data' must be of a vector type, was 'NULL'
Calls: <Anonymous> ... .rasterObjectFromFile -> .rasterFromRasterFile -> readIniFile -> matrix
In addition: There were 50 or more warnings (use warnings() to see the first 50)
Execution halted
```

the slide has 0 tumor-positive patches and 1 til-positive patch. could that be the issue?

@lthealy

**Comment by lthealy** [comment]
This is in the rasterization step, so it probably doesn't have to do with the actual prediction values. Those aren't used until later. How many tissue patches are there overall?

**Comment by kaczmarj** [comment]
78 tumor patches and 268 TIL patches.

**Comment by lthealy** [comment]
I historically have trimmed out low res files being that they are primarily used for quick quality scans. If "low_res" images are consistently generated, we may want to include a flag to skip them in the alignment step.
