### ISSUE TITLE
Docker image not compatible with arm64 Mac (M1)

### ISSUE THREAD

**Issue by lthealy** [SBU-BMI/tumor-til-survival-analysis#14]
`run-v1.sh` runs end to end on Ubuntu, but identical calls with identical inputs fail on my Mac instance

After pulling both align and survival images, the following warning is printed:
<img width="1065" alt="image" src="https://user-images.githubusercontent.com/40005359/225973365-d61b09f3-a199-4bba-9361-4bf6c1b857eb.png">

The error is shown here:
<img width="658" alt="image" src="https://user-images.githubusercontent.com/40005359/225973314-c5fbb405-a521-4032-a099-2efed931cc1d.png">

**Building multi-platform container and may need to add --platform tag to facilitate correct build pull**

**Comment by kaczmarj** [comment]
using docker desktop, one can build amd64 and arm64 versions of the til_align docker image like this:

```
cd til_align
docker build --tag=tilalign --platform=linux/amd64,linux/arm64 .
```

**Comment by kaczmarj** [comment]
i am building the docker images for amd64 and arm64 now. i am using the following commands:

```bash
git clone git@github.com:SBU-BMI/til_align.git
cd til_align/
git checkout missingPairs
# Set up builder for multi-platform builds. 
docker buildx create --name mybuilder --driver docker-container --bootstrap --use
# Build docker image.
docker buildx build -t kaczmarj/tilalign:68c2a3b --platform=linux/amd64,linux/arm64 .
# Push docker images.
# todo...
```
